import type {
  Difficulty,
  RepairCase,
  RepairOutcome,
  SafetyClassification,
} from './domain.ts';

type Scenario = {
  category: string;
  brand: string;
  model: string;
  product: string;
  problem: string;
  symptoms: string[];
  safety: SafetyClassification;
  difficulty: Difficulty;
  test: string;
  observed: string;
  fix: string;
  parts: string[];
  outcome: RepairOutcome;
  cost: number;
  minutes: number;
  votes: [number, number, number];
};

const scenarios: Scenario[] = [
  [
    'Game controllers',
    'Sony',
    'CFI-ZCT1W',
    'DualSense Wireless Controller',
    'Left analog stick drifts upward during gameplay',
    ['stick drift', 'ghost input', 'deadzone'],
    'low_risk',
    'easy',
    'Test the stick in the controller input monitor without touching it.',
    'The Y axis rests at -0.18 and spikes upward.',
    'Cleaned the stick perimeter with electronics-safe air and recalibrated the controller.',
    ['electronics-safe air'],
    'fixed',
    8,
    24,
    [18, 12, 2],
  ],
  [
    'Game controllers',
    'Sony',
    'CFI-ZCT1W',
    'DualSense Wireless Controller',
    'Right stick slowly pulls the camera left',
    ['stick drift', 'camera movement', 'right stick'],
    'moderate_risk',
    'advanced',
    'Increase the in-game deadzone by five percent and compare.',
    'Drift becomes less visible but the input monitor still shows movement.',
    'Replaced the worn joystick potentiometer module.',
    ['joystick module', 'lead-free solder'],
    'fixed',
    14,
    52,
    [22, 9, 3],
  ],
  [
    'Game controllers',
    'Microsoft',
    '1914',
    'Xbox Wireless Controller',
    'Left stick input jumps near the outer edge',
    ['stick drift', 'input jump', 'left stick'],
    'low_risk',
    'easy',
    'Rotate the stick slowly around the full gate in a tester.',
    'A discontinuity appears between 70 and 85 percent travel.',
    'Removed debris around the stick shaft; no internal disassembly.',
    ['soft brush'],
    'improved',
    4,
    18,
    [11, 6, 4],
  ],
  [
    'Game controllers',
    'Nintendo',
    'HAC-015',
    'Joy-Con',
    'Character walks right without input',
    ['stick drift', 'ghost input', 'Joy-Con'],
    'moderate_risk',
    'moderate',
    'Run the console stick calibration screen and release the stick.',
    'The marker settles outside the center circle.',
    'Replaced the joystick assembly and recalibrated.',
    ['Joy-Con joystick assembly'],
    'fixed',
    12,
    35,
    [31, 20, 5],
  ],
  [
    'Game controllers',
    '8BitDo',
    'Ultimate 2.4G',
    'Ultimate Wireless Controller',
    'Face button intermittently misses presses',
    ['button input', 'intermittent', 'B button'],
    'low_risk',
    'easy',
    'Log fifty button presses in the input tester.',
    'Seven B-button presses are not registered.',
    'Cleaned around the button cap; the missed presses continued.',
    ['soft brush'],
    'not_fixed',
    3,
    15,
    [7, 1, 6],
  ],
  [
    'Computer mice',
    'Logitech',
    'G502 HERO',
    'Gaming Mouse',
    'Left click registers twice',
    ['double click', 'left button', 'duplicate input'],
    'moderate_risk',
    'moderate',
    'Use a click counter to compare physical and registered clicks.',
    'One hundred presses produce 119 registered clicks.',
    'Replaced the worn primary microswitch.',
    ['D2F microswitch'],
    'fixed',
    9,
    38,
    [44, 28, 6],
  ],
  [
    'Computer mice',
    'Logitech',
    'MX Master 3S',
    'Wireless Mouse',
    'Scroll wheel stops free-spinning',
    ['scroll wheel', 'ratchet mode', 'intermittent'],
    'low_risk',
    'easy',
    'Toggle ratchet and free-spin modes ten times.',
    'The mode changes only after several toggles.',
    'Cleared compacted dust around the wheel mechanism.',
    ['electronics-safe air'],
    'fixed',
    5,
    20,
    [16, 10, 2],
  ],
  [
    'Computer mice',
    'Razer',
    'Basilisk V3',
    'Gaming Mouse',
    'Pointer skips on a cloth mouse pad',
    ['tracking', 'pointer skip', 'sensor'],
    'low_risk',
    'easy',
    'Test tracking on clean white paper.',
    'Tracking is smooth on paper but skips on the cloth pad.',
    'Cleaned the sensor lens and replaced the worn mouse pad.',
    ['microfiber cloth'],
    'fixed',
    10,
    12,
    [9, 7, 1],
  ],
  [
    'Computer mice',
    'Generic',
    'M185-compatible',
    'Wireless Mouse',
    'Mouse disconnects every few minutes',
    ['disconnect', 'wireless', 'battery'],
    'low_risk',
    'easy',
    'Install a known-good battery and test for fifteen minutes.',
    'No disconnect occurs with the known-good battery.',
    'Replaced the depleted battery and cleaned the battery contacts.',
    ['AA battery'],
    'fixed',
    2,
    10,
    [12, 10, 0],
  ],
  [
    'Mechanical keyboards',
    'Keychron',
    'K2 V2',
    'Wireless Mechanical Keyboard',
    'E key produces repeated characters',
    ['key chatter', 'duplicate characters', 'E key'],
    'low_risk',
    'easy',
    'Use a switch tester page for fifty deliberate presses.',
    'Nine presses produce duplicate E characters.',
    'Replaced the hot-swap switch and cleaned the socket.',
    ['mechanical switch'],
    'fixed',
    6,
    17,
    [35, 26, 3],
  ],
  [
    'Mechanical keyboards',
    'Ducky',
    'One 2 Mini',
    'Mechanical Keyboard',
    'Spacebar does not return evenly',
    ['stabilizer', 'spacebar', 'sticky key'],
    'low_risk',
    'moderate',
    'Remove only the keycap and press both ends of the stabilizer.',
    'The left stabilizer binds before returning.',
    'Cleaned and re-lubricated the accessible stabilizer wire.',
    ['keyboard lubricant'],
    'fixed',
    7,
    28,
    [15, 8, 2],
  ],
  [
    'Mechanical keyboards',
    'NuPhy',
    'Air75',
    'Low-profile Keyboard',
    'Bluetooth typing lags after wake',
    ['bluetooth', 'input lag', 'wake'],
    'low_risk',
    'easy',
    'Compare wired and Bluetooth input after five minutes of sleep.',
    'Wired input is immediate; Bluetooth takes eight seconds.',
    'Updated keyboard firmware and removed the stale Bluetooth pairing.',
    ['none'],
    'fixed',
    0,
    16,
    [13, 9, 1],
  ],
  [
    'Mechanical keyboards',
    'Corsair',
    'K70 RGB MK.2',
    'Mechanical Keyboard',
    'Several keys remain dim after reboot',
    ['RGB lighting', 'dim LEDs', 'multiple keys'],
    'moderate_risk',
    'advanced',
    'Load a solid white lighting profile at full brightness.',
    'Three adjacent LEDs remain dim in every profile.',
    'Internal LED repair was deferred to a qualified electronics technician.',
    ['none'],
    'professional_repair_required',
    0,
    12,
    [5, 0, 1],
  ],
  [
    'Computer peripherals',
    'Anker',
    '341 USB-C Hub',
    'USB-C Hub',
    'External monitor flickers through HDMI',
    ['HDMI', 'flicker', 'USB-C hub'],
    'low_risk',
    'easy',
    'Connect the monitor directly using the same cable.',
    'The direct connection is stable.',
    'Replaced the hub after its HDMI output failed under two displays.',
    ['replacement hub'],
    'replacement_required',
    35,
    25,
    [14, 6, 2],
  ],
  [
    'Computer peripherals',
    'Wacom',
    'CTL-472',
    'One Drawing Tablet',
    'Pen pressure drops out mid-stroke',
    ['pen pressure', 'intermittent', 'tablet'],
    'low_risk',
    'easy',
    'Test pressure in the driver diagnostics panel.',
    'Pressure drops to zero when the cable is moved.',
    'Replaced the damaged USB cable.',
    ['micro-USB cable'],
    'fixed',
    7,
    14,
    [12, 10, 1],
  ],
  [
    'Computer peripherals',
    'Elgato',
    'Stream Deck MK.2',
    'Stream Deck',
    'Keys show stale icons after sleep',
    ['display', 'stale icons', 'sleep'],
    'low_risk',
    'easy',
    'Restart only the Stream Deck service.',
    'All icons refresh after the service restarts.',
    'Updated the Stream Deck application and disabled USB selective suspend for the port.',
    ['none'],
    'fixed',
    0,
    19,
    [10, 7, 0],
  ],
  [
    'Audio',
    'Sony',
    'WH-1000XM4',
    'Wireless Headphones',
    'Left hinge creaks and feels loose',
    ['hinge', 'creak', 'loose joint'],
    'low_risk',
    'moderate',
    'Compare hinge play on the left and right sides.',
    'The left hinge has two millimeters more lateral movement.',
    'Installed a model-specific hinge reinforcement bracket.',
    ['hinge bracket'],
    'improved',
    11,
    32,
    [25, 14, 4],
  ],
  [
    'Audio',
    'Bose',
    'QC35 II',
    'Wireless Headphones',
    'Headphones power off when the switch is released',
    ['power switch', 'intermittent power', 'headphones'],
    'moderate_risk',
    'advanced',
    'Hold the switch gently in the on position.',
    'Power remains on only while pressure is applied.',
    'Internal switch replacement was recommended to a professional.',
    ['none'],
    'professional_repair_required',
    0,
    10,
    [8, 1, 1],
  ],
  [
    'Audio',
    'Audio-Technica',
    'ATH-M50x',
    'Studio Headphones',
    'Audio cuts out in the right earcup',
    ['audio dropout', 'right channel', 'cable'],
    'low_risk',
    'easy',
    'Test with a second detachable cable.',
    'The dropout disappears with the second cable.',
    'Replaced the detachable audio cable.',
    ['3.5 mm locking cable'],
    'fixed',
    13,
    8,
    [19, 17, 0],
  ],
  [
    'Small electronics',
    'Apple',
    'A2337',
    'MacBook Air',
    'Laptop runs hot and fanless performance slows',
    ['overheating', 'blocked vent', 'slow performance'],
    'low_risk',
    'easy',
    'Inspect exterior vents and measure idle temperature after cleaning the desk surface.',
    'Lint is visible at the rear vent and idle temperature is elevated.',
    'Cleared the exterior vent with the computer powered off; no disassembly.',
    ['soft brush'],
    'improved',
    4,
    18,
    [17, 11, 2],
  ],
  [
    'Small electronics',
    'Raspberry Pi',
    '4 Model B',
    'Single-board Computer',
    'USB-C power disconnects when cable moves',
    ['USB-C', 'intermittent power', 'cable'],
    'low_risk',
    'easy',
    'Test with a known-good power supply without moving the board.',
    'Power is stable with the known-good supply.',
    'Replaced the worn USB-C power cable.',
    ['USB-C power supply'],
    'fixed',
    12,
    12,
    [13, 12, 0],
  ],
  [
    'Small electronics',
    'Amazon',
    'Kindle Paperwhite 11',
    'E-reader',
    'Charging only works at one cable angle',
    ['charging', 'USB-C', 'intermittent'],
    'moderate_risk',
    'moderate',
    'Inspect the port with a light while the device is off.',
    'Compacted lint is visible at the rear of the connector.',
    'Had the port professionally cleaned to avoid connector damage.',
    ['none'],
    'professional_repair_required',
    18,
    20,
    [21, 11, 2],
  ],
  [
    'Bicycles',
    'Trek',
    'FX 2 Disc',
    'Hybrid Bicycle',
    'Rear brake rubs once per wheel rotation',
    ['brake rub', 'disc rotor', 'rear wheel'],
    'moderate_risk',
    'moderate',
    'Spin the rear wheel slowly and observe rotor clearance.',
    'The rotor approaches the outer pad at one point each rotation.',
    'A bicycle technician trued the rotor and verified braking.',
    ['none'],
    'professional_repair_required',
    25,
    30,
    [18, 9, 1],
  ],
  [
    'Bicycles',
    'Specialized',
    'Sirrus X 2.0',
    'Hybrid Bicycle',
    'Chain skips under hard pedaling',
    ['chain skip', 'drivetrain', 'load'],
    'professional_recommended',
    'advanced',
    'Stop riding under load and inspect chain wear with a gauge.',
    'The chain measures beyond the replacement threshold.',
    'A bicycle technician replaced the chain and inspected the cassette.',
    ['chain'],
    'professional_repair_required',
    45,
    40,
    [24, 14, 2],
  ],
  [
    'Bicycles',
    'Brompton',
    'C Line',
    'Folding Bicycle',
    'Folding pedal clicks on every rotation',
    ['pedal click', 'folding mechanism', 'noise'],
    'moderate_risk',
    'moderate',
    'Rotate the pedal by hand with the bicycle stationary.',
    'A click is felt at the same bearing position.',
    'Replaced the folding pedal assembly and verified retention.',
    ['folding pedal'],
    'fixed',
    38,
    35,
    [9, 6, 1],
  ],
  [
    'Home office',
    'Herman Miller',
    'Aeron Classic',
    'Office Chair',
    'Chair slowly sinks during the day',
    ['gas cylinder', 'height loss', 'chair'],
    'moderate_risk',
    'moderate',
    'Mark the seat height and leave the chair unloaded for one hour.',
    'The unloaded height drops by three centimeters.',
    'Replaced the sealed gas cylinder using the manufacturer-approved part.',
    ['gas cylinder'],
    'fixed',
    42,
    45,
    [28, 20, 4],
  ],
  [
    'Home office',
    'IKEA',
    'MARKUS',
    'Office Chair',
    'One caster no longer rolls smoothly',
    ['caster', 'wheel', 'drag'],
    'low_risk',
    'easy',
    'Swap the suspect caster with another position.',
    'The drag follows the caster.',
    'Replaced the damaged caster.',
    ['replacement caster'],
    'fixed',
    9,
    9,
    [13, 12, 0],
  ],
  [
    'Home office',
    'Brother',
    'HL-L2350DW',
    'Laser Printer',
    'Paper feeds crooked and jams',
    ['paper feed', 'jam', 'crooked paper'],
    'low_risk',
    'easy',
    'Test five sheets from a fresh, correctly loaded stack.',
    'The left edge enters before the right edge.',
    'Cleaned the accessible pickup roller and adjusted the paper guides.',
    ['lint-free cloth'],
    'fixed',
    3,
    26,
    [20, 13, 3],
  ],
  [
    'Home office',
    'Epson',
    'ET-2850',
    'Inkjet Printer',
    'Black prints show horizontal gaps',
    ['print quality', 'banding', 'black ink'],
    'low_risk',
    'easy',
    'Run the built-in nozzle check.',
    'The black grid has several missing segments.',
    'Ran one approved print-head cleaning cycle and waited before retesting.',
    ['none'],
    'improved',
    0,
    22,
    [16, 9, 2],
  ],
  [
    'Cables and adapters',
    'Anker',
    'PowerLine III',
    'USB-C Cable',
    'Charging stops when the connector bends',
    ['USB-C cable', 'intermittent connection', 'charging'],
    'low_risk',
    'easy',
    'Test the device with a known-good cable.',
    'Charging remains stable with the known-good cable.',
    'Retired and replaced the damaged cable rather than repairing it.',
    ['USB-C cable'],
    'replacement_required',
    10,
    5,
    [18, 15, 0],
  ],
].map((row) => ({
  category: row[0],
  brand: row[1],
  model: row[2],
  product: row[3],
  problem: row[4],
  symptoms: row[5],
  safety: row[6],
  difficulty: row[7],
  test: row[8],
  observed: row[9],
  fix: row[10],
  parts: row[11],
  outcome: row[12],
  cost: row[13],
  minutes: row[14],
  votes: row[15],
})) as Scenario[];

const BASE_DATE = new Date('2026-08-25T16:00:00.000Z');

export const seedCases: RepairCase[] = scenarios.map((item, index) => {
  const caseNumber = 1001 + index;
  const id = `MS-${caseNumber}`;
  const created = new Date(
    BASE_DATE.getTime() + index * 31 * 60 * 1000,
  ).toISOString();
  return {
    id,
    category: item.category,
    brand: item.brand,
    model: item.model,
    product_name: item.product,
    problem_description: item.problem,
    symptoms: item.symptoms,
    status: item.outcome,
    safety_classification: item.safety,
    difficulty: item.difficulty,
    demo_record: true,
    created_at: created,
    updated_at: created,
    diagnostic_steps: [
      {
        id: `${id}-DS-1`,
        sequence: 1,
        test: item.test,
        reason:
          'Start with the least invasive test that separates common causes.',
        expected_result: 'The observation should narrow the next safe action.',
        observed_result: item.observed,
        notes: 'Synthetic demo observation.',
        status: 'completed',
        created_at: created,
      },
    ],
    repair_attempts: [
      {
        id: `${id}-RA-1`,
        repair_description: item.fix,
        parts_used: item.parts,
        estimated_cost: item.cost,
        difficulty: item.difficulty,
        created_at: created,
      },
    ],
    outcome: {
      id: `${id}-RO-1`,
      outcome: item.outcome,
      final_fix: item.fix,
      cost: item.cost,
      time_minutes: item.minutes,
      notes:
        'Synthetic demo outcome used to demonstrate structured repair evidence.',
      created_at: created,
    },
    votes: {
      helpful: item.votes[0],
      worked_for_me: item.votes[1],
      did_not_work: item.votes[2],
    },
  };
});
